language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libusb-1.0-0:i386
    - libusb-1.0-0-dev
    - libudev-dev

script:
- cd commandline
- make
- make blink1-tiny-server
- make package
- make package-tiny-server
- ls -alrth
- cd ..

before_deploy:
- DFILE1=$(ls commandline/blink1-tool*zip)
- DFILE2=$(ls commandline/blink1-lib*zip)
- DFILE3=$(ls commandline/blink1-tiny-server*zip)

deploy:
  provider: releases
  api_key:
    secure: gXX2CJ5j9INqRaHzPBoYfMbM3etTruK/sQSnoBfIfw9g3qFRUwSQ8vAkdYMmdKs3Zt/z4e07dbS0q08TL/7rR7Y2R6QOZXTIIzFKjixcJAXcsqZwzNyPO1BZInkoJ/XJZ3TlQLTy3dzhKJ2BIm79rwPjuVufElEVgiigQxbk8L6wHYBk+yu+E4PS/yp8xKabJiMIwttZeU/iW+zRMNWk9LEkYvoHHx3+pAC3NIwYXqX+yoCdzYLmVYqq+rbfgtBkNUo8ZjKZWojSW4DN8mjuekr7t4lqLs6s8+cTvncYjIMcObyWWvLvYOg18c5Z0n7p3CU7cFgzqrjX+gBQdTu3KEf9eM8tKQAUjkhp8zBcAYxIHOUeAKpbiNrB5azPbNny/17xMag7v3QEg8ORgaOin6jv7rpR5ai8eURDTJseNz1tcFzsLyFJ82gc7DLttM3vrDB291rcezbOjOLHHF/hZNhqGrk2iHbbtQVCWO3vtBYZ9KniseqQdlvGArXKKgmKfXWib5r8+mOdMdkIDrcekXdkLa/BqibgA0hF9eHqM0CwFiR5S3naAP44IbzVSYpJTB0yQCwj56BLmgOORSpyGcfSeGezcXNIDZRSjtoL3pYkP5Tu3dhflxfL6PGagXwjJ3klhG0mEZC0L/t5JSaA4R1LWd9uU5Hu5634WL9R5cs=
  file:
    - "${DFILE1}"
    - "${DFILE2}"
    - "${DFILE3}"
  on:
    repo: todbot/blink1
